version: '3.8'
networks:
  dev:
services:
  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - "5000:5000"
      volumes:
        - './nginx.conf:/etc/nginx/nginx.conf'
      depends_on:
        - api
      networks:
        - dev
  api:
    build: ./api
    working_dir: /api
    platform: linux/arm64
    container_name: fastapi-api
    expose:
      - "8000"
    volumes:
      - ./db:/data  # Монтируем папку с базой данных
      - ./api:/api
      - ./static:/api/static
      - ./templates:/api/templates
    networks:
      - dev
  
  